source_ids:
- elections-ab-new-citizen-initiative-2026-01-02
- elections-ab-current-petitions
- elections-ab-initiative-process
- elections-ab-referendum
- alberta-referendum-2026
- elections-ab-bill-23-2026-04-29
- globalnews-court-pauses-verification-2026-04-12
- alberta-citizen-initiative-act
- alberta-referendum-act
