source_ids:
- elections-ab-referendum
- alberta-referendum-2026
- elections-ab-bill-23-2026-04-29
- elections-ab-current-petitions
- elections-ab-new-citizen-initiative-2026-01-02
- alberta-premiers-address-2026-02-19
- globalnews-court-pauses-verification-2026-04-12
