source_ids:
- alberta-energy
- alberta-oil-sands
- alberta-royalty-overview
- alberta-energy-regulator
- responsible-energy-development-act
- cer-pipeline-profiles
- cer-canada-oil-imports-exports
- cer-canadas-energy-future-2023
- impact-assessment-act
- iaac-impact-assessment-process-overview
- canada-fisheries-act
- canada-undrip-act
- scc-secession-reference
- alberta-emissions-reduction-energy-development-plan
- eccc-greenhouse-gas-emissions
